.github/workflows/ci-cd.yml, .github/workflows/deploy.yml, vercel.json
- vercel 세팅을 위해 action에서 yml 파일을 추가하고, 설정 파일도 추가했습니다.
- 상세한 변경사항을 bullet로 적어주세요
> ex) #23
> UI 변경이 있다면 스크린샷 첨부
=> chore: vercel 파일 생성

.prettierrc, eslint.config.js, package-lock.json, package.json, yarn.lock
- 무엇을 추가/변경했는지 요약해주세요
- 상세한 변경사항을 bullet로 적어주세요
> ex) #23
> UI 변경이 있다면 스크린샷 첨부
=> chore : set up eslint and prettier

src/pages/Main/MainPage.css.ts, src/shared/styles/tokens.css.ts
- 디자인시스템에 맞게 폰트 토큰 다시 수정했습니다 !
=> chore: 폰트 스타일 수정

package.json, src/pages/ComponentTest/ComponentTest.tsx, src/router/router.tsx, src/shared/assets/icon/ic_R_seat.svg, src/shared/assets/icon/ic_S_seat.svg, src/shared/components/SeatSelectChip/SeatSelectChip.css.ts, src/shared/components/SeatSelectChip/SeatSelectChip.tsx, yarn.lock
좌석 선택 칩 컴포넌트 구현했습니다 
- 컴포넌트 테스트를 위한 임시 라우팅 추가해두었습니다. 필요하신 분들은 /component-test 에서 작성하신 컴포넌트들 import 해서 테스트 하시면 됩니다! 
- vanilla-extract recipe 추가해두어서 pull 받으시고 yarn 으로 설치 후에 작업하시면 됩니다. 
- #6 
https://github.com/user-attachments/assets/ba69c7c9-28ff-439f-af36-64db4794d09b
=> feat: 좌석 선택 컴포넌트 구현

src/shared/components/BookingButton/BookingButton.css.ts, src/shared/components/BookingButton/BookingButton.tsx, src/shared/components/ChangeButton/ChangeButton.css.ts, src/shared/components/ChangeButton/ChangeButton.tsx, src/shared/components/RegisterButton/Register.css.ts, src/shared/components/RegisterButton/RegisterButton.tsx
- 예매, 일시변경, 등록 버튼 컴포넌트 구현했습니다 
- 사용하는 페이지에서 아래와 같이 작성해주시고, 기능 들어가면 Props  추가 전달해주시면 됩니다. (버튼 상위 태그에 alignItems: 'center' 작성)
```tsx
<div className={styles.buttonContainer}>
<BookingButton type="button">예매하기</BookingButton>
<ChangeButton type="button">일시변경</ChangeButton>
<RegisterButton type="submit">등록</RegisterButton>
</div>
```
- #10
=> feat: 예매, 일시변경, 등록 버튼 컴포넌트 구현

src/pages/Main/MainPage.tsx, src/shared/components/Popup/Popup.css.ts, src/shared/components/Popup/Popup.tsx
좌석 페이지 팝업창 구현
- "확인" 버튼 클릭 시 visible 변경처리
- 뒤에 팝업 배경지까지 PopArea로 함께 포함 
> ex) #39
=> feat: 좌석 페이지 팝업창 구현

src/pages/Main/MainPage.tsx, src/shared/components/Badge/Badge.css.ts, src/shared/components/Badge/Badge.tsx
뱃지 type에 따른 컴포넌트 분기
type이
'hot'이면 빨간 뱃지
'단독판매'이면 파란 뱃지
> ex) #40
=> feat : 뱃지 컴포넌트

src/pages/Main/MainPage.tsx, src/shared/components/main/Perform/InfoCard.css.ts, src/shared/components/main/Perform/InfoCard.tsx
메인페이지
공연정보 공통 컴포넌트
isrank 에 true/false에 따라서
공연 포스터위에 랭크 레이어가 들어가짐!!
isrank={true} 후에 rank에 숫자 부여
> ex) #42
=> feat : 메인페이지 공연박스 컴포넌트

src/pages/Main/MainPage.tsx, src/shared/components/TimeDeal/TimeDeal.css.ts, src/shared/components/TimeDeal/TimeDeal.tsx
타임딜 뱃지 컴포넌
- 상세한 변경사항을 bullet로 적어주세요
> ex) #49
=> feat: 타임딜 뱃지 컴포넌트

src/shared/components/HomeMoreButton/HomeMoreButton.css.ts, src/shared/components/HomeMoreButton/HomeMoreButton.tsx
- 홈화면의 전체보기 버튼 컴포넌트 파일 추가
- 상세한 변경사항을 bullet로 적어주세요
> #58 
> UI 변경이 있다면 스크린샷 첨부
=> feat: 홈 전체보기 버튼 컴포넌트 파일 추가

src/shared/components/BankInfo/BankInfoCard.css.ts, src/shared/components/BankInfo/BankInfoCard.tsx, src/shared/components/HomeMoreButton/HomeMoreButton.css.ts, src/shared/components/HomeMoreButton/HomeMoreButton.tsx
- 빌드 에러가 떠서 포맷팅 해서 다시 올려두었습니다 
- ci cd에서 lint 관련 에러가 뜨면 `yarn lint --fix && yarn format` 명령어를 터미널에 입력해서 전체 코드 포맷팅 해주세요! 
- `git add .` 하고 `yarn lint:staged` 명령어를 입력하면 현재 내가 추가한 파일들에 대해서만 검사해주니까 커밋 전에 하시면 빌드 에러 방지에 좀 더 좋을 거 같슴다. ㅎ (관련 설정은 package.json 확인하시면 됩니당) 
- Closes #63
=> chore: 빌드 오류 해결을 위한 포맷팅 수행

src/pages/SeatSelect/SeatSelectPage.css.ts, src/pages/SeatSelect/SeatSelectPage.tsx, src/pages/SeatSelect/components/SeatCard/Seat.css.ts, src/pages/SeatSelect/components/SeatCard/Seat.tsx, src/pages/SeatSelect/components/SeatCard/SeatCard.css.ts, src/pages/SeatSelect/components/SeatCard/SeatCard.tsx, src/pages/SeatSelect/components/SeatCard/SeatRow.css.ts, src/pages/SeatSelect/components/SeatCard/SeatRow.tsx, src/pages/SeatSelect/components/StageText/StageText.css.ts, src/pages/SeatSelect/components/StageText/StageText.tsx, src/pages/SeatSelect/types/SeatData.ts, src/router/router.tsx
- 좌석 선택 컴포넌트를 구현하였습니다. 
- Seat는 좌석 등급에 따라서 색상을 구분하고, 선택하면 파란 좌석으로 변경되며 선택한 좌석 인덱스를 보여지도록 했습니다. 선택되지 않은 좌석들은 회색 처리하고 클릭이 비활성화 되도록 했습니다! 
- SeatRow는 하나의 행을 만드는 녀석이고 통로 부분은 마진처리 해두었습니당 
- SeatCard는 좌석 전체를 렌더링하고, spacer를 두어서 R열 S열 사이에 통로 마진 처리 했습니다. 
- Closes #60 
https://github.com/user-attachments/assets/a5c9d641-a790-4501-b242-31df2773b071
=> feat: 좌석 선택 컴포넌트 구현 

src/pages/SelectDate/SelectDatePage.css.ts, src/pages/SelectDate/SelectDatePage.tsx, src/router/router.tsx, src/shared/components/Calendar/Calendar.css.ts, src/shared/components/Calendar/Calendar.tsx, src/shared/components/CardContentInfo/CardContentInfo.css.ts, src/shared/components/CardContentInfo/CardContentInfo.tsx, src/shared/components/DateReservationCard/DateReservationCard.css.ts, src/shared/styles/tokens.css.ts
예매 날짜 선택 페이지
1. 달력 컴포넌트 연결 & 공연 정보 연결
2. 해당 날짜 선택에 따른 예매박스 핸들링
3. 뷰 레이아웃
- Closes #74
=> feat : 날짜 선택 페이지

src/pages/Main/MainPage.tsx, src/pages/Main/components/CategoryTab/CategoryTab.css.ts, src/pages/Main/components/CategoryTab/CategoryTab.tsx, src/pages/Main/components/Genre/Genre.css.ts, src/pages/Main/components/Genre/Genre.tsx, src/shared/components/HomeMoreButton/HomeMoreButton.css.ts, src/shared/components/main/Perform/InfoCard.css.ts
메인페이지 병합전 : 장르별 랭킹 섹션
1. InfoCard 맵핑
2. 카테고리 맵핑
3. 스크롤
- Closes #79
=> feat : 메인페이지 - 장르별 맵핑 섹션

src/shared/network/axiosInstance.ts, src/shared/network/baseResponse.ts, src/shared/network/request.ts
- base response 값 변경 
- axios instance 반환값 변경
- request 함수 내부 수정 
- CORS 에러 때문에 임시로 withCredentials: false 해두었습니다.
- 응답 성공하면 우선 확인할 수 있도록 토스트 메세지랑 콘솔로 찍어두었습니다! 
- Closes #96
=> fix: API 세팅 수정

src/pages/Main/MainPage.css.ts, src/pages/Main/MainPage.tsx, src/pages/Main/api/types.ts, src/pages/Main/components/Discount/Discout.tsx, src/pages/Main/components/Discount/DiscoutCard.tsx, src/shared/components/main/NavBar/NavBar.css.ts
nav 컴포넌트 홈에 붙이고 스타일 수정했습니다.
할인 중 컴포넌트 필드 이름도 수정했습니다. (openDate -> startDate)
- Closes #106
=> design: 홈에 nav 추가하고 스타일 수정, 필요없는 주석 제거

src/shared/components/CardContentInfo/CardContentInfo.css.ts, src/shared/components/DateReservationCard/DateReservationCard.tsx
- 날짜 선택 페이지의 컴포넌트에 누락된 텍스트 추가
- 날짜 선택 페이지의 공연 정보 카드에 한 글자만 넘어가서 넓이를 사아아아알짝 넓혔습니다.
- Closes #119
=> chore: 날짜 선택 페이지 컴포넌트 수정

src/shared/components/CardContentInfo/CardContentInfo.css.ts, src/shared/components/DateReservationCard/DateReservationCard.tsx
chore: 날짜 선택 페이지 컴포넌트 수정 (#120)
=> release: 3차 배포

src/pages/SeatSelect/SeatSelectPage.tsx, src/pages/SeatSelect/components/SeatCard/SeatRow.tsx, src/shared/components/CardContentInfo/CardContentInfo.css.ts, src/shared/components/DateReservationCard/DateReservationCard.tsx
=> release: 4차 배포

src/pages/Main/MainPage.tsx, src/pages/Main/components/Genre/Genre.tsx, src/pages/Main/components/skeleton/ImageSkeleton.tsx, src/pages/Main/components/skeleton/ImageSkeletonList.tsx, src/pages/Main/components/skeleton/Skelton.css.ts, src/shared/components/Spinner/Spinner.tsx
- 홈의 장르 섹션에 스켈레톤을 추가했습니다.
- 스피너에 ';' 같이 출력되서  지웠습니다 
- 장르 섹션의 infoCard에 맞는 스켈레톤 ui를 생성하고 리스트를 통해 count 숫자만큼 뿌리도록 설정했습니다.
- 제대로 확인하려면 느린 네트워크 설정해서 많은 인내심이 필요합니다 ㅎㅎ;;
- Closes #128 
https://github.com/user-attachments/assets/7139b740-96ab-49b0-8683-dc52dd22e298
=> feat: 홈 장르 섹션 스켈레톤 추가

src/pages/Main/components/NOL PLAY/NolPlaySection.css.ts, src/pages/Main/components/NOL PLAY/NolPlaySection.tsx
- NOL PLAY의 큰 이미지에 border-radius 추가
- NOL PLAY의 큰 이미지에 border-radius가 빠져있었네요.. 있었는데? 없어요..
- 
- Closes #132
=> style: NOL PLAY border-radius 추가
